version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: knowledge_sharing_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge_sharing
    ports:
      - "5432:5432"
    volumes:
      - knowledge_sharing_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  knowledge_sharing_postgres_data:
    name: knowledge_sharing_postgres_data 